export const businessTemplates: Record<string, { 
  label: string; 
  icon: string; 
  description: string; 
  categories: string[];
  units: string[];
  currencies: string[];
}> = {
  candles: {
    label: "Candles",
    icon: "🕯️",
    description: "Hand-poured candles, wax melts, and home fragrance.",
    categories: [
      "Wax",
      "Wick",
      "Fragrance Oil",
      "Essential Oil",
      "Vessel",
      "Lid",
      "Label & Sticker",
      "Dust Cover",
      "Packaging",
      "Additive",
      "Dye",
      "Warning Label",
    ],
    units: ["oz", "lb", "g", "kg"],
    currencies: ["USD", "CAD", "EUR", "GBP"],
  },
  baking: {
    label: "Baking & Confections",
    icon: "🍪",
    description: "Baked goods, confections, and dessert products.",
    categories: [
      "Flour",
      "Sugar",
      "Butter",
      "Eggs",
      "Baking Powder",
      "Vanilla Extract",
      "Chocolate",
      "Frosting",
      "Sprinkles",
      "Packaging",
      "Yeast",
      "Cocoa Powder",
      "Fruit Filling",
    ],
    units: ["g", "kg", "oz", "lb", "cup"],
    currencies: ["USD", "CAD", "EUR", "GBP"],
  },
  bath_body: {
    label: "Bath & Body",
    icon: "🧴",
    description: "Skincare, body care, and beauty products.",
    categories: [
      "Shea Butter",
      "Cocoa Butter",
      "Coconut Oil",
      "Essential Oil",
      "Fragrance Oil",
      "Colorant",
      "Mica Powder",
      "Mold",
      "Packaging",
      "Preservative",
      "Emulsifier",
      "Bottle & Jar",
      "Label",
    ],
    units: ["oz", "lb", "g", "kg", "ml"],
    currencies: ["USD", "CAD", "EUR", "GBP"],
  },
  soap: {
    label: "Soap Making",
    icon: "🧼",
    description: "Cold process, hot process, and melt & pour soaps.",
    categories: [
      "Lye",
      "Coconut Oil",
      "Olive Oil",
      "Palm Oil",
      "Castor Oil",
      "Shea Butter",
      "Fragrance Oil",
      "Essential Oil",
      "Colorant",
      "Mica Powder",
      "Mold",
      "Packaging",
      "Additive",
      "Exfoliant",
    ],
    units: ["oz", "lb", "g", "kg"],
    currencies: ["USD", "CAD", "EUR", "GBP"],
  },
  jewelry: {
    label: "Jewelry",
    icon: "💍",
    description: "Handmade jewelry and accessories.",
    categories: [
      "Beads",
      "Wire",
      "Chain",
      "Clasp",
      "Earring Hook",
      "Pendant",
      "Gemstone",
      "Metal Sheet",
      "Jump Ring",
      "Packaging",
      "Tool",
    ],
    units: ["pc", "g", "mm", "in"],
    currencies: ["USD", "CAD", "EUR", "GBP"],
  },
  ceramics: {
    label: "Ceramics & Pottery",
    icon: "🏺",
    description: "Handmade ceramics, pottery, and clay goods.",
    categories: [
      "Clay",
      "Glaze",
      "Underglaze",
      "Slip",
      "Kiln Furniture",
      "Tool",
      "Packaging",
      "Additive",
      "Stain",
    ],
    units: ["lb", "kg", "oz", "g"],
    currencies: ["USD", "CAD", "EUR", "GBP"],
  },
  other: {
    label: "Other / Custom",
    icon: "✨",
    description: "Start with a blank canvas and create your own categories.",
    categories: [],
    units: ["pc", "oz", "lb", "g", "kg", "ml", "L"],
    currencies: ["USD", "CAD", "EUR", "GBP"],
  },
};
