export const businessTemplates: Record<string, { label: string; icon: string; description: string; categories: string[] }> = {
  candles: {
    label: "Candles",
    icon: "🕯️",
    description: "Wax, wicks, fragrance oils, and vessels.",
    categories: [
      "Wax",
      "Wick",
      "Fragrance Oil",
      "Vessel",
      "Lid",
      "Label & Sticker",
      "Dust Cover",
      "Packaging",
      "Additive",
    ],
  },
  baking: {
    label: "Baking",
    icon: "🍞",
    description: "Flour, sugar, butter, and more.",
    categories: [
      "Flour",
      "Sugar",
      "Butter",
      "Eggs",
      "Baking Powder",
      "Vanilla Extract",
      "Chocolate",
      "Frosting",
      "Sprinkles",
      "Packaging",
    ],
  },
  bath_body: {
    label: "Bath & Body",
    icon: "🧼",
    description: "Shea butter, oils, molds, and packaging.",
    categories: [
      "Shea Butter",
      "Cocoa Butter",
      "Coconut Oil",
      "Essential Oil",
      "Fragrance Oil",
      "Colorant",
      "Mica Powder",
      "Mold",
      "Packaging",
    ],
  },
  soap: {
    label: "Soap Making",
    icon: "🫧",
    description: "Lye, oils, molds, and scents.",
    categories: [
      "Lye",
      "Coconut Oil",
      "Olive Oil",
      "Palm Oil",
      "Fragrance Oil",
      "Colorant",
      "Mold",
      "Packaging",
      "Additive",
    ],
  },
  other: {
    label: "Other",
    icon: "🎨",
    description: "Start with a blank slate and create your own categories.",
    categories: [],
  },
};